# Generated by Django 6.0.5 on 2026-05-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("apartment", "Квартира"),
                            ("house", "Дом"),
                            ("room", "Комната"),
                            ("studio", "Студия"),
                        ],
                        max_length=20,
                    ),
                ),
                ("city", models.CharField(max_length=80)),
                ("district", models.CharField(blank=True, max_length=120)),
                ("address", models.CharField(max_length=220)),
                ("price_per_month", models.PositiveIntegerField()),
                ("rooms", models.PositiveSmallIntegerField(default=1)),
                ("area", models.DecimalField(decimal_places=2, max_digits=7)),
                ("floor", models.PositiveSmallIntegerField(default=1)),
                ("total_floors", models.PositiveSmallIntegerField(default=1)),
                ("has_furniture", models.BooleanField(default=False)),
                ("has_parking", models.BooleanField(default=False)),
                ("pets_allowed", models.BooleanField(default=False)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("photo_url", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Свободно"),
                            ("booked", "Забронировано"),
                            ("hidden", "Скрыто"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["city"], name="properties__city_74fa1a_idx"),
                    models.Index(
                        fields=["district"], name="properties__distric_2e026e_idx"
                    ),
                    models.Index(
                        fields=["property_type"], name="properties__propert_5c7790_idx"
                    ),
                    models.Index(
                        fields=["status"], name="properties__status_6427a0_idx"
                    ),
                    models.Index(
                        fields=["price_per_month"],
                        name="properties__price_p_0baf56_idx",
                    ),
                ],
            },
        ),
    ]
